CREATE TABLE trips (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    uuid VARCHAR(36) UNIQUE NOT NULL,
    driver_id BIGINT NOT NULL,
    uber_trip_id VARCHAR(100) UNIQUE NOT NULL,
    started_at DATETIME NOT NULL,
    ended_at DATETIME NOT NULL,
    duration_minutes INT GENERATED ALWAYS AS (TIMESTAMPDIFF(MINUTE, started_at, ended_at)) STORED,
    distance_km DECIMAL(10,2) NOT NULL,
    fare_value DECIMAL(10,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'BRL',
    fare_base DECIMAL(10,2) DEFAULT 0,
    fare_distance DECIMAL(10,2) DEFAULT 0,
    fare_time DECIMAL(10,2) DEFAULT 0,
    toll_charge DECIMAL(10,2) DEFAULT 0,
    service_fee DECIMAL(10,2) DEFAULT 0,
    city VARCHAR(100),
    start_latitude DECIMAL(10,8),
    start_longitude DECIMAL(11,8),
    end_latitude DECIMAL(10,8),
    end_longitude DECIMAL(11,8),
    status VARCHAR(50) DEFAULT 'COMPLETED',
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE,
    INDEX idx_driver_id (driver_id),
    INDEX idx_ended_at (ended_at),
    INDEX idx_driver_ended (driver_id, ended_at),
    INDEX idx_status (status),
    FULLTEXT INDEX ft_city (city)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
